"""Strategy engine for executing trading strategies and generating signals."""

import asyncio
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Callable, Awaitable, Any
import structlog

from src.strategy.config import StrategyConfig, EntryCondition, ExitCondition, PriceNearLevelCondition
from src.exchange.connector import MarketData
from src.indicators.calculator import IndicatorCalculator


logger = structlog.get_logger(__name__)


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    strategy_name: str
    symbol: str
    side: str  # 'buy' or 'sell'
    quantity: float
    price: Optional[float]
    timestamp: datetime
    reason: str  # Description of why signal was generated
    
    def __post_init__(self):
        """Validate signal after initialization."""
        if self.side not in ['buy', 'sell']:
            raise ValueError(f"Invalid signal side: {self.side}")
        if self.quantity <= 0:
            raise ValueError(f"Invalid signal quantity: {self.quantity}")


@dataclass
class StrategyState:
    """State for a running strategy."""
    config: StrategyConfig
    is_active: bool = True
    last_signal: Optional[Signal] = None
    last_signal_time: Optional[datetime] = None
    entry_time: Optional[datetime] = None
    entry_price: Optional[float] = None
    has_position: bool = False
    error_count: int = 0
    last_error: Optional[str] = None
    
    # Previous indicator values for cross detection
    previous_indicators: Dict[str, float] = None
    
    def __post_init__(self):
        if self.previous_indicators is None:
            self.previous_indicators = {}


class StrategyEngine:
    """
    Strategy engine that executes trading strategies and generates signals.
    
    Handles:
    - Strategy registration
    - Market data processing
    - Condition evaluation (entry and exit)
    - Signal generation
    - Concurrent strategy execution
    - State isolation per trading pair
    - Error isolation per strategy
    """
    
    def __init__(
        self,
        indicator_calculator: IndicatorCalculator,
        signal_callback: Optional[Callable[[Signal], Awaitable[None]]] = None
    ):
        """
        Initialize strategy engine.
        
        Args:
            indicator_calculator: Calculator for technical indicators
            signal_callback: Optional callback to receive generated signals
        """
        self.indicator_calculator = indicator_calculator
        self.signal_callback = signal_callback
        
        # Strategy states: {strategy_name: StrategyState}
        self._strategies: Dict[str, StrategyState] = {}
        
        # State isolation per trading pair: {(strategy_name, symbol): state_data}
        self._pair_states: Dict[tuple, Dict[str, Any]] = {}
        
        # Lock for thread-safe operations
        self._lock = asyncio.Lock()
        
        # Running flag
        self._running = False
        
        logger.info("strategy_engine_initialized")
    
    async def register_strategy(self, config: StrategyConfig) -> None:
        """
        Register a strategy for execution.
        
        Args:
            config: Strategy configuration
        """
        async with self._lock:
            if config.name in self._strategies:
                logger.warning(
                    "strategy_already_registered",
                    strategy=config.name
                )
                return
            
            # Create strategy state
            state = StrategyState(config=config)
            self._strategies[config.name] = state
            
            # Initialize pair state
            pair_key = (config.name, config.symbol)
            self._pair_states[pair_key] = {
                'last_update': None,
                'market_data': None,
                'indicators': {}
            }
            
            logger.info(
                "strategy_registered",
                strategy=config.name,
                symbol=config.symbol,
                timeframes=config.timeframes
            )
    
    async def unregister_strategy(self, strategy_name: str) -> None:
        """
        Unregister a strategy.
        
        Args:
            strategy_name: Name of strategy to unregister
        """
        async with self._lock:
            if strategy_name not in self._strategies:
                logger.warning(
                    "strategy_not_found",
                    strategy=strategy_name
                )
                return
            
            # Remove strategy state
            state = self._strategies[strategy_name]
            del self._strategies[strategy_name]
            
            # Remove pair state
            pair_key = (strategy_name, state.config.symbol)
            if pair_key in self._pair_states:
                del self._pair_states[pair_key]
            
            logger.info("strategy_unregistered", strategy=strategy_name)
    
    async def process_market_data(self, data: MarketData) -> None:
        """
        Process market data and evaluate all strategies for this symbol.
        
        This method runs strategies concurrently without blocking.
        
        Args:
            data: Market data to process
        """
        # Find all strategies for this symbol
        strategies_to_process = []
        
        async with self._lock:
            for name, state in self._strategies.items():
                if state.config.symbol == data.symbol and state.is_active:
                    strategies_to_process.append((name, state))
        
        if not strategies_to_process:
            return
        
        logger.debug(
            "processing_market_data",
            symbol=data.symbol,
            strategies=len(strategies_to_process),
            timestamp=data.timestamp
        )
        
        # Process strategies concurrently
        tasks = [
            self._process_strategy(name, state, data)
            for name, state in strategies_to_process
        ]
        
        await asyncio.gather(*tasks, return_exceptions=True)
    
    async def _process_strategy(
        self,
        strategy_name: str,
        state: StrategyState,
        data: MarketData
    ) -> None:
        """
        Process a single strategy with error isolation.
        
        Args:
            strategy_name: Name of strategy
            state: Strategy state
            data: Market data
        """
        try:
            # Update pair state
            pair_key = (strategy_name, state.config.symbol)
            self._pair_states[pair_key]['last_update'] = datetime.now()
            self._pair_states[pair_key]['market_data'] = data
            
            # Add market data to indicator calculator
            for timeframe in state.config.timeframes:
                await self.indicator_calculator.add_market_data(data, timeframe)
            
            # Calculate indicators
            indicators = await self._calculate_indicators(state.config, data.symbol)
            
            if indicators is None:
                # Not enough data yet
                return
            
            # Store indicators in pair state
            self._pair_states[pair_key]['indicators'] = indicators
            
            # Check if this is a test strategy
            if state.config.strategy_type == "test":
                # Test mode: just log data reception and indicator values
                logger.info(
                    "test_strategy_data_received",
                    strategy=strategy_name,
                    symbol=data.symbol,
                    price=data.close,
                    volume=data.volume,
                    timestamp=data.timestamp.isoformat(),
                    indicators=indicators,
                    timeframes=state.config.timeframes
                )
                
                # Update previous indicators for next iteration
                state.previous_indicators = indicators.copy()
                return
            
            # Regular strategy: evaluate conditions and generate signals
            if not state.has_position:
                # Check entry conditions
                signal = await self._evaluate_entry_conditions(
                    state,
                    data,
                    indicators
                )
                
                if signal:
                    await self._emit_signal(signal, state)
            else:
                # Check exit conditions
                signal = await self._evaluate_exit_conditions(
                    state,
                    data,
                    indicators
                )
                
                if signal:
                    await self._emit_signal(signal, state)
            
            # Update previous indicators for cross detection
            state.previous_indicators = indicators.copy()
            
        except Exception as e:
            # Error isolation: log error but don't stop other strategies
            state.error_count += 1
            state.last_error = str(e)
            
            logger.error(
                "strategy_processing_error",
                strategy=strategy_name,
                symbol=data.symbol,
                error=str(e),
                error_count=state.error_count,
                exc_info=True
            )
    
    async def _calculate_indicators(
        self,
        config: StrategyConfig,
        symbol: str
    ) -> Optional[Dict[str, float]]:
        """
        Calculate all indicators for a strategy.
        
        Args:
            config: Strategy configuration
            symbol: Trading symbol
            
        Returns:
            Dict mapping indicator names to values, or None if insufficient data
        """
        indicators = {}
        
        for name, indicator_config in config.indicators.items():
            try:
                if indicator_config.type == "rsi":
                    value = await self.indicator_calculator.calculate_rsi(
                        symbol=symbol,
                        timeframe=indicator_config.timeframe,
                        period=indicator_config.period
                    )
                elif indicator_config.type == "ema":
                    value = await self.indicator_calculator.calculate_ema(
                        symbol=symbol,
                        timeframe=indicator_config.timeframe,
                        period=indicator_config.period
                    )
                else:
                    logger.warning(
                        "unknown_indicator_type",
                        indicator=name,
                        type=indicator_config.type
                    )
                    continue
                
                if value is None:
                    # Not enough data yet
                    return None
                
                indicators[name] = value
                
            except Exception as e:
                logger.error(
                    "indicator_calculation_error",
                    indicator=name,
                    error=str(e),
                    exc_info=True
                )
                return None
        
        return indicators
    
    async def _evaluate_entry_conditions(
        self,
        state: StrategyState,
        data: MarketData,
        indicators: Dict[str, float]
    ) -> Optional[Signal]:
        """
        Evaluate entry conditions for a strategy.
        
        Args:
            state: Strategy state
            data: Market data
            indicators: Calculated indicator values
            
        Returns:
            Buy signal for long strategies or sell signal for short strategies if conditions met, None otherwise
        """
        config = state.config
        
        # All entry conditions must be met
        all_met = True
        reasons = []
        
        for condition in config.entry_conditions:
            met, reason = await self._evaluate_entry_condition(
                condition,
                indicators,
                state.previous_indicators
            )
            
            if met:
                reasons.append(reason)
            else:
                all_met = False
                break
        
        if all_met:
            # Generate signal based on position direction
            # Long: entry = buy, Short: entry = sell
            signal_side = 'buy' if config.position_direction == 'long' else 'sell'
            
            signal = Signal(
                strategy_name=config.name,
                symbol=config.symbol,
                side=signal_side,
                quantity=config.position_size,
                price=None,  # Market order
                timestamp=datetime.now(),
                reason="; ".join(reasons)
            )
            
            logger.info(
                "entry_signal_generated",
                strategy=config.name,
                symbol=config.symbol,
                position_direction=config.position_direction,
                side=signal_side,
                reason=signal.reason
            )
            
            return signal
        
        return None
    
    async def _evaluate_entry_condition(
        self,
        condition: EntryCondition,
        indicators: Dict[str, float],
        previous_indicators: Dict[str, float]
    ) -> tuple[bool, str]:
        """
        Evaluate a single entry condition.
        
        Args:
            condition: Entry condition to evaluate
            indicators: Current indicator values
            previous_indicators: Previous indicator values (for cross detection)
            
        Returns:
            Tuple of (condition_met, reason_string)
        """
        try:
            if condition.type == "less_than":
                indicator_value = indicators.get(condition.indicator)
                if indicator_value is None:
                    return False, ""
                
                met = indicator_value < condition.value
                reason = f"{condition.indicator}={indicator_value:.2f} < {condition.value}"
                return met, reason
            
            elif condition.type == "greater_than":
                indicator_value = indicators.get(condition.indicator)
                if indicator_value is None:
                    return False, ""
                
                met = indicator_value > condition.value
                reason = f"{condition.indicator}={indicator_value:.2f} > {condition.value}"
                return met, reason
            
            elif condition.type == "cross_above":
                ind1_current = indicators.get(condition.indicator1)
                ind2_current = indicators.get(condition.indicator2)
                ind1_previous = previous_indicators.get(condition.indicator1)
                ind2_previous = previous_indicators.get(condition.indicator2)
                
                if None in [ind1_current, ind2_current, ind1_previous, ind2_previous]:
                    return False, ""
                
                # Cross above: was below, now above
                met = (ind1_previous <= ind2_previous) and (ind1_current > ind2_current)
                reason = f"{condition.indicator1} crossed above {condition.indicator2}"
                return met, reason
            
            elif condition.type == "cross_below":
                ind1_current = indicators.get(condition.indicator1)
                ind2_current = indicators.get(condition.indicator2)
                ind1_previous = previous_indicators.get(condition.indicator1)
                ind2_previous = previous_indicators.get(condition.indicator2)
                
                if None in [ind1_current, ind2_current, ind1_previous, ind2_previous]:
                    return False, ""
                
                # Cross below: was above, now below
                met = (ind1_previous >= ind2_previous) and (ind1_current < ind2_current)
                reason = f"{condition.indicator1} crossed below {condition.indicator2}"
                return met, reason
            
            else:
                logger.warning(
                    "unknown_entry_condition_type",
                    type=condition.type
                )
                return False, ""
                
        except Exception as e:
            logger.error(
                "entry_condition_evaluation_error",
                condition_type=condition.type,
                error=str(e),
                exc_info=True
            )
            return False, ""
    
    async def _evaluate_price_near_level_condition(
        self,
        condition: PriceNearLevelCondition,
        state: StrategyState,
        current_price: float
    ) -> tuple[bool, str]:
        """
        Evaluate if price is near support or resistance level.
        
        Args:
            condition: Price near level condition
            state: Strategy state
            current_price: Current market price
            
        Returns:
            Tuple of (condition_met, reason_string)
        """
        config = state.config
        
        # Get the target level
        if condition.level == "support":
            if config.support_level is None:
                logger.error(
                    "missing_support_level",
                    strategy=config.name,
                    message="price_near_level condition requires support_level to be defined"
                )
                return False, "support_level not defined"
            level_price = config.support_level
            level_name = "support"
        else:  # resistance
            if config.resistance_level is None:
                logger.error(
                    "missing_resistance_level",
                    strategy=config.name,
                    message="price_near_level condition requires resistance_level to be defined"
                )
                return False, "resistance_level not defined"
            level_price = config.resistance_level
            level_name = "resistance"
        
        # Calculate distance as percentage
        distance_percent = abs(current_price - level_price) / level_price * 100
        
        # Check if within proximity threshold
        proximity_threshold = config.level_proximity_percent
        is_near = distance_percent <= proximity_threshold
        
        # Track proximity zone transitions for logging
        pair_key = (config.name, config.symbol)
        if pair_key not in self._pair_states:
            self._pair_states[pair_key] = {}
        
        # Check if this is a zone entry/exit
        was_near_key = f"was_near_{level_name}"
        was_near = self._pair_states[pair_key].get(was_near_key, False)
        
        if is_near and not was_near:
            # Entering proximity zone
            logger.info(
                "entering_level_proximity",
                strategy=config.name,
                symbol=config.symbol,
                level=level_name,
                level_price=level_price,
                current_price=current_price,
                distance_percent=round(distance_percent, 3),
                threshold_percent=proximity_threshold
            )
            self._pair_states[pair_key][was_near_key] = True
        elif not is_near and was_near:
            # Exiting proximity zone
            logger.info(
                "exiting_level_proximity",
                strategy=config.name,
                symbol=config.symbol,
                level=level_name,
                level_price=level_price,
                current_price=current_price,
                distance_percent=round(distance_percent, 3),
                threshold_percent=proximity_threshold
            )
            self._pair_states[pair_key][was_near_key] = False
        
        # Build reason string
        if is_near:
            reason = (
                f"Price {current_price:.2f} within {distance_percent:.2f}% "
                f"of {level_name} {level_price:.2f}"
            )
        else:
            reason = (
                f"Price {current_price:.2f} is {distance_percent:.2f}% "
                f"from {level_name} {level_price:.2f} (threshold: {proximity_threshold}%)"
            )
        
        logger.debug(
            "price_near_level_evaluated",
            strategy=config.name,
            level=level_name,
            is_near=is_near,
            distance_percent=round(distance_percent, 3),
            reason=reason
        )
        
        return is_near, reason
    
    async def _evaluate_exit_conditions(
        self,
        state: StrategyState,
        data: MarketData,
        indicators: Dict[str, float]
    ) -> Optional[Signal]:
        """
        Evaluate exit conditions for a strategy.
        
        Args:
            state: Strategy state
            data: Market data
            indicators: Calculated indicator values
            
        Returns:
            Sell signal for long strategies or buy signal for short strategies if any condition met, None otherwise
        """
        config = state.config
        
        # Any exit condition can trigger exit
        for condition in config.exit_conditions:
            met, reason = await self._evaluate_exit_condition(
                condition,
                state,
                data
            )
            
            if met:
                # Generate signal based on position direction
                # Long: exit = sell, Short: exit = buy
                signal_side = 'sell' if config.position_direction == 'long' else 'buy'
                
                signal = Signal(
                    strategy_name=config.name,
                    symbol=config.symbol,
                    side=signal_side,
                    quantity=config.position_size,  # Close full position
                    price=None,  # Market order
                    timestamp=datetime.now(),
                    reason=reason
                )
                
                logger.info(
                    "exit_signal_generated",
                    strategy=config.name,
                    symbol=config.symbol,
                    position_direction=config.position_direction,
                    side=signal_side,
                    reason=signal.reason
                )
                
                return signal
        
        return None
    
    async def _evaluate_exit_condition(
        self,
        condition: ExitCondition,
        state: StrategyState,
        data: MarketData
    ) -> tuple[bool, str]:
        """
        Evaluate a single exit condition.
        
        Args:
            condition: Exit condition to evaluate
            state: Strategy state
            data: Market data
            
        Returns:
            Tuple of (condition_met, reason_string)
        """
        try:
            if condition.type == "take_profit":
                if state.entry_price is None:
                    return False, ""
                
                profit_pct = ((data.close - state.entry_price) / state.entry_price) * 100
                met = profit_pct >= condition.percent
                reason = f"Take profit: {profit_pct:.2f}% >= {condition.percent}%"
                return met, reason
            
            elif condition.type == "stop_loss":
                if state.entry_price is None:
                    return False, ""
                
                loss_pct = ((state.entry_price - data.close) / state.entry_price) * 100
                met = loss_pct >= condition.percent
                reason = f"Stop loss: {loss_pct:.2f}% >= {condition.percent}%"
                return met, reason
            
            elif condition.type == "time_exceeds":
                if state.entry_time is None:
                    return False, ""
                
                elapsed = (datetime.now() - state.entry_time).total_seconds()
                met = elapsed >= condition.seconds
                reason = f"Time exceeded: {elapsed:.0f}s >= {condition.seconds}s"
                return met, reason
            
            elif condition.type == "support_resistance":
                if condition.direction == "below":
                    met = data.close < condition.price
                    reason = f"Price {data.close} below support {condition.price}"
                else:  # "above"
                    met = data.close > condition.price
                    reason = f"Price {data.close} above resistance {condition.price}"
                return met, reason
            
            elif condition.type == "end_of_day":
                # Parse time_utc (HH:MM format)
                target_hour, target_minute = map(int, condition.time_utc.split(":"))
                now = datetime.utcnow()
                
                # Check if current time matches or exceeds target time
                met = (now.hour > target_hour) or (now.hour == target_hour and now.minute >= target_minute)
                reason = f"End of day: {now.hour:02d}:{now.minute:02d} >= {condition.time_utc}"
                return met, reason
            
            else:
                logger.warning(
                    "unknown_exit_condition_type",
                    type=condition.type
                )
                return False, ""
                
        except Exception as e:
            logger.error(
                "exit_condition_evaluation_error",
                condition_type=condition.type,
                error=str(e),
                exc_info=True
            )
            return False, ""
    
    async def _emit_signal(self, signal: Signal, state: StrategyState) -> None:
        """
        Emit a signal and update strategy state.
        
        Args:
            signal: Signal to emit
            state: Strategy state
        """
        # Update state
        state.last_signal = signal
        state.last_signal_time = signal.timestamp
        
        if signal.side == 'buy':
            state.has_position = True
            state.entry_time = signal.timestamp
            # Entry price will be updated when order fills
        elif signal.side == 'sell':
            state.has_position = False
            state.entry_time = None
            state.entry_price = None
        
        # Call signal callback if registered
        if self.signal_callback:
            try:
                await self.signal_callback(signal)
            except Exception as e:
                logger.error(
                    "signal_callback_error",
                    strategy=signal.strategy_name,
                    error=str(e),
                    exc_info=True
                )
    
    async def update_position_state(
        self,
        strategy_name: str,
        has_position: bool,
        entry_price: Optional[float] = None
    ) -> None:
        """
        Update position state for a strategy (called after order fills).
        
        Args:
            strategy_name: Name of strategy
            has_position: Whether strategy has an open position
            entry_price: Entry price if position opened
        """
        async with self._lock:
            if strategy_name not in self._strategies:
                logger.warning(
                    "update_position_unknown_strategy",
                    strategy=strategy_name
                )
                return
            
            state = self._strategies[strategy_name]
            state.has_position = has_position
            
            if has_position and entry_price is not None:
                state.entry_price = entry_price
            elif not has_position:
                state.entry_price = None
                state.entry_time = None
            
            logger.debug(
                "position_state_updated",
                strategy=strategy_name,
                has_position=has_position,
                entry_price=entry_price
            )
    
    def get_strategy_state(self, strategy_name: str) -> Optional[StrategyState]:
        """
        Get state for a strategy.
        
        Args:
            strategy_name: Name of strategy
            
        Returns:
            StrategyState or None if not found
        """
        return self._strategies.get(strategy_name)
    
    def get_all_strategies(self) -> Dict[str, StrategyState]:
        """
        Get all registered strategies.
        
        Returns:
            Dict mapping strategy names to states
        """
        return self._strategies.copy()
    
    async def get_statistics(self) -> Dict[str, Any]:
        """
        Get statistics about strategy engine.
        
        Returns:
            Dict with statistics
        """
        async with self._lock:
            stats = {
                "total_strategies": len(self._strategies),
                "active_strategies": sum(1 for s in self._strategies.values() if s.is_active),
                "strategies_with_positions": sum(1 for s in self._strategies.values() if s.has_position),
                "strategies_with_errors": sum(1 for s in self._strategies.values() if s.error_count > 0),
                "strategies": {}
            }
            
            for name, state in self._strategies.items():
                stats["strategies"][name] = {
                    "symbol": state.config.symbol,
                    "is_active": state.is_active,
                    "has_position": state.has_position,
                    "error_count": state.error_count,
                    "last_signal_time": state.last_signal_time.isoformat() if state.last_signal_time else None
                }
            
            return stats
